config/routes.rb
Rails.application.routes.draw do
  get 'users/new'

  get 'home/index'

  resources :alumns
  
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alumn.rb
class Alumn < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/parent.rb
class Parent < ApplicationRecord
  belongs_to :parent
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  validates :name, presence:true, length:{maximum: 50}
  VALID_EMAIL_REGEX= /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence:true, length:{maximum: 255},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }                  
end

app/controllers/alumns_controller.rb
class AlumnsController < ApplicationController

  def index
    @alumns= Alumn.all
  end

  def new
    @alumn= Alumn.new
  end

  def show
    @alumn= Alumn.find(params[:id])
  end

  def edit
    @alumn = Alumn.find(params[:id])
  end

  def update
    @alumn = Alumn.find(params[:id])
    if @alumn.update(alumn_params)
      redirect_to @alumn
    else
      render 'edit'
    end
  end

  def create
    @alumn = Alumn.new(alumn_params)

    if @alumn.save
      redirect_to @alumn
    else
      render 'new'
    end
  end

  def destroy
    @alumn=Alumn.find(params[:id])
    @alumn.destroy

    redirect_to alumns_path
  end

  private
    def alumn_params
      params.require(:alumn).permit(:registry_alumn,:name_alumn,:class_alumn,:address_alumn,:phone_alumn,:birth_date_alumn,:sex_alumn)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/parents_controller.rb
class ParentsController < ApplicationController

  def create
    @alumn = Alumn.find(params[:alumn_id])
    @parent = alumn.parent.create(parent_params)

    redirect_to alumn_path(@alumn)
  end

  private
    def parent_params
      params.require(:parent).permit(:cpf_parent,:name_parent,:address_parent,:phone_parent,:sex_parent,:rg_parent)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end
end

app/helpers/alumn_helper.rb
module AlumnHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/alumns/_form.html.erb
<%= form_for (@alumn) do |f| %>
  <p>
    <%= f.label :registry_alumn%><br>
    <%= f.text_field :registry_alumn %>
  </p>
  <p>
    <%= f.label :name_alumn%><br>
    <%= f.text_field :name_alumn %>
  </p>
  <p>
    <%= f.label :class_alumn%><br>
    <%= f.text_field :class_alumn %>
  </p>
  <p>
    <%= f.label :address_alumn%><br>
    <%= f.text_field :address_alumn %>
  </p>
  <p>
    <%= f.label :phone_alumn%><br>
    <%= f.telephone_field :phone_alumn %>
  </p>
  <p>
    <%= f.label :birth_date_alumn%><br>
    <%= f.date_field :birth_date_alumn %>
  </p>
  <p>
    <div class="field">
      <%= f.label :sex_alumn %><br>
      <%= f.label :sex_alumn, "Masculino", :value => "masculino"  %>
      <%= f.radio_button :sex_alumn, 'masculino' %>
      <%= f.label :sex_alumn, "Feminino", :value => "feminino" %>
      <%= f.radio_button :sex_alumn, 'feminino' %>
    </div>
  </p>
  <p>
    <%= f.submit%>
  </p>

  <% end%>

app/views/alumns/edit.html.erb
<h1>Editar Aluno</h1>

<%= render 'form' %>

<%=link_to 'Voltar', alumns_path %>

app/views/alumns/index.html.erb
<h1>Alunos</h1>
<p>
<%= link_to 'Novo aluno', new_alumn_path%>
</p>
<table>
  <% @alumns.each do |alumn| %>
    <tr>
      <td><%=alumn.registry_alumn%></td>
      <td><%=alumn.name_alumn%></td>
      <td><%=link_to 'Mostrar', alumn_path(alumn)%></td>
      <td><%=link_to 'Editar',edit_alumn_path(alumn) %></td>
      <td><%=link_to 'Deletar',alumn_path(alumn), method: :delete, data: {confirm: 'Tem certeza que deseja deletar?'} %></td>
    </tr>
  <% end %>
</table>

app/views/alumns/new.html.erb
<h1>Novo Aluno</h1>

<%= render 'form' %>

<%=link_to 'Voltar', alumns_path %>

app/views/alumns/show.html.erb
<h1><%=@alumn.name_alumn %></h1>

<hr>

<table>
  <tr>
    <th>Matrícula</th>
    <td><%=@alumn.registry_alumn %></td>
  </tr>
  <tr>
    <th>Endereço</th>
    <td><%=@alumn.address_alumn %></td>
  </tr>
  <tr>
    <th>Telfone</th>
    <td><%=@alumn.phone_alumn %></td>
  </tr>
  <tr>
    <th>Sexo</th>
    <td><%=@alumn.sex_alumn %></td>
  </tr>
  <tr>
    <th>Data de nascimento</th>
    <td><%=@alumn.birth_date_alumn %></td>
  </tr>
</table>

<%= link_to 'Voltar', alumns_path %>

app/views/alumns/teste.html.erb
<h1><%=@alumn.name_alumn %></h1>

<hr>

<table>
  <tr>
    <th>Matrícula</th>
    <td><%=@alumn.registry_alumn %></td>
  </tr>
  <tr>
    <th>Endereço</th>
    <td><%=@alumn.address_alumn %></td>
  </tr>

  <%=link_to 'Voltar', alumns_path %>

app/views/home/index.html.erb
<h1>Welcome to school</h1>
<%=link_to 'Alunos', alumns_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Escola</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>